require 'momo/resource_types/vpc'
require 'momo/resource_types/gateway'
require 'momo/resource_types/route_table'
require 'momo/resource_types/security_group'
require 'momo/resource_types/instance'
require 'momo/resource_types/subnet'
